In [1]:
import torch
import torch.nn as nn

# -------------------------------
# 1) Define the input image (5x5)
# -------------------------------
image = torch.tensor([
    [1., 2., 0., 1., 3.],
    [0., 1., 2., 2., 1.],
    [3., 1., 0., 1., 0.],
    [2., 2., 1., 0., 1.],
    [0., 1., 3., 2., 2.]
])

# Convert to shape (batch, channels, height, width) -> (1,1,5,5)
image = image.unsqueeze(0).unsqueeze(0)

# -----------------------------------------
# 2) Define the Sharpen Kernel (3x3 filter)
# -----------------------------------------
kernel = torch.tensor([
    [0., -1.,  0.],
    [-1.,  5., -1.],
    [0., -1.,  0.]
])

# ---------------------------------------------
# 3) Create a Conv2D Layer with the exact filter
# ---------------------------------------------
conv = nn.Conv2d(
    in_channels=1,     # image has 1 channel
    out_channels=1,    # produce 1 feature map
    kernel_size=3,     # 3x3 filter
    stride=1,
    padding=0,
    bias=False         # no bias to focus only on kernel
)

# Set the conv layer's weights to our kernel
conv.weight.data = kernel.unsqueeze(0).unsqueeze(0)  # (1,1,3,3)

# ----------------------------
# 4) Apply the convolution
# ----------------------------
output = conv(image)

# ----------------------------
# 5) Print everything neatly
# ----------------------------
print("Input Image (5x5):")
print(image[0, 0])
print("\nSharpen Kernel (3x3):")
print(kernel)
print("\nOutput Feature Map (3x3):")
print(output[0, 0])

Input Image (5x5):
tensor([[1., 2., 0., 1., 3.],
        [0., 1., 2., 2., 1.],
        [3., 1., 0., 1., 0.],
        [2., 2., 1., 0., 1.],
        [0., 1., 3., 2., 2.]])

Sharpen Kernel (3x3):
tensor([[ 0., -1.,  0.],
        [-1.,  5., -1.],
        [ 0., -1.,  0.]])

Output Feature Map (3x3):
tensor([[ 0.,  7.,  5.],
        [-1., -5.,  3.],
        [ 5.,  0., -5.]], grad_fn=<SelectBackward0>)
